name: fuzz-micro-job

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ci-test
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: recursive

    - name: Build and test
      run: |
        cmake --version
        set -o pipefail
        mkdir build
        cd build
        bash ${{ github.workspace }}/tests/fuzz.sh 5 2>&1 | tee fuzz-log.txt
        cd ..

    - name: Show report
      run: |
        cat build/report.txt
        echo "Fuzzing completed"

    - name: upload-artifact
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: fuzz-log-${{ github.sha }}
        path: "build/fuzz-log.txt"


